use role SYSADMIN;
use warehouse WH_DBT_TRANSFORM;
use database DEMO_DB;
use schema RAW;

call DEMO_DB.RAW.export_import_tables(
  'SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS,
   SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER,
   SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM,
   SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART,
   SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER'
);
